version: '3.8'

services:
  indexer:
    build: ./src/py_movie_db
    volumes:
      - ./src/py_movie_db/:/usr/src/py_movie_db/
    env_file:
      - ./.env.dev
    networks:
      - postcard-dev-net
    profiles:
      - indexer

  server:
    build: ./src/py_movie_db
    volumes:
      - ./src/py_movie_db/:/usr/src/py_movie_db/
    env_file:
      - ./.env.dev
    ports:
      - 8000:8000
    networks:
      - postcard-dev-net
    profiles:
      - src

networks:
  postcard-dev-net:
    external: true
    name: postcard-dev-net
