version: '3.8'

services:
  movie_server:
    build: ./src/py_movie_db
    volumes:
      - ./src/py_movie_db/:/usr/src/py_movie_db/
    env_file:
      - ./.env.dev
    ports:
      - 8101:80
    networks:
      - movie-dev-net
    profiles:
      - movie_server

  rs_movie_server:
    build: ./src/rs_movie_db
    env_file:
      - ./.env.dev
    ports:
      - 8000:8000
    networks:
      - movie-dev-net
    profiles:
      - rs_movie_server

  movie_seed:
    build: ./src/movie_indexer_job
    env_file:
      - ./.env.dev
    profiles:
      - movie_seed
    command: python seed.py

  movie_indexer:
    build: ./src/movie_indexer_job
    env_file:
      - ./.env.dev
    profiles:
      - movie_indexer

  load_runner:
    build: ./src/load_runner
    volumes:
      - ./src/load_runner/:/usr/src/load_runner/
    env_file:
      - ./.env.dev
    ports:
      - 8089:80
    networks:
      - movie-dev-net
    profiles:
      - load_runner

networks:
  movie-dev-net:
    external: true
    name: movie-dev-net
