version: '3.8'

services:
  movie_server:
    build: ./src/py_movie_db
    volumes:
      - ./src/py_movie_db/:/usr/src/py_movie_db/
    env_file:
      - ./.env.dev
    ports:
      - 8101:80
    networks:
      - movie-dev-net
    profiles:
      - movie_server

networks:
  movie-dev-net:
    external: true
    name: movie-dev-net
