version: '3.8'

services:
  indexer:
    build: ./indexer
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    networks:
      - postcard-dev-net
    profiles:
      - indexer

  server:
    build: ./server
    volumes:
      - ./backend/:/usr/src/backend/
    env_file:
      - ./.env.dev
    networks:
      - postcard-dev-net
    profiles:
      - server

networks:
  postcard-dev-net:
    external: true
    name: postcard-dev-net
