apiVersion: v1
data:
  AWS_DEFAULT_REGION: us-east-2
  AWS_INBOX_BUCKET_NAME: movie-db-inbox
  AWS_STORAGE_BUCKET_NAME: movie-db-store
  AWS_ARCHIVE_BUCKET_NAME: movie-db-archive
kind: ConfigMap
metadata:
  name: movies-env
