apiVersion: batch/v1
kind: Job
metadata:
  name: seed-db
spec:
  template:
    spec:
      containers:
      - env:
          - name: AWS_DEFAULT_REGION
            valueFrom:
              configMapKeyRef:
                key: AWS_DEFAULT_REGION
                name: movies-env
          - name: AWS_INBOX_BUCKET_NAME
            valueFrom:
              configMapKeyRef:
                key: AWS_INBOX_BUCKET_NAME
                name: movies-env
          - name: AWS_STORAGE_BUCKET_NAME
            valueFrom:
              configMapKeyRef:
                key: AWS_STORAGE_BUCKET_NAME
                name: movies-env
          - name: AWS_ARCHIVE_BUCKET_NAME
            valueFrom:
              configMapKeyRef:
                key: AWS_ARCHIVE_BUCKET_NAME
                name: movies-env
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: AWS_ACCESS_KEY_ID
                optional: false
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: AWS_SECRET_ACCESS_KEY
                optional: false
        name: movie-indexer-seed
        image: 192.168.1.85:5000/movie_indexer:latest
        imagePullPolicy: Always
        command: ["python", "seed.py"]
      restartPolicy: Never
  backoffLimit: 4
