apiVersion: v1
kind: Service
metadata:
  name: {{ include "movie-db-chart.fullname" . }}-rs
  labels:
    {{- include "movie-db-chart.labels" . | nindent 4 }}
    app: {{ include "movie-db-chart.fullname" . }}-rs
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    {{- include "movie-db-chart.selectorLabels" . | nindent 4 }}
    app: {{ include "movie-db-chart.fullname" . }}-movie-server-rs
