ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - path: /locust(/|$)(.*)
      pathType: Prefix
loadtest:
  name: movie-loadtest
  locust_host: http://192.168.1.85/movie-db-api
  locust_locustfile_configmap: movie-locustfile
